name: 03-Cypress Tests

on:
  workflow_run:
    workflows: ["02-SonarCloud"]
    branches: [ "main", "dev" ]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  cypress:
    name: Cypress Basic Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'frontend/package.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start frontend server
        working-directory: ./frontend
        run: |
          npm run build
          npx serve dist/frontend/browser -l 3000 &
          sleep 5

      - name: Run Cypress tests
        working-directory: ./frontend
        run: npm run cypress:run
        env:
          CYPRESS_BASE_URL: http://localhost:3000

      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: frontend/cypress/screenshots
